#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#PS1='[\u@\h \W]\$ '

# Git branch in bashprompt
source "/usr/share/git/completion/git-prompt.sh"

# Sets PS1 in a function so its easier to understand. =P
set_ps1 () {
local RESET="\[$(tput sgr0)\]"
local MAGENTA="\[$(tput setaf 5)\]"
local BOLD="\[$(tput bold)\]"
local GREEN="\[$(tput setaf 2)\]"
local LIGHTGREEN="\[$(tput setaf 10)\]"
local RED="\[$(tput setaf 1)\]"
local GIT="\$(__git_ps1 '(%s) ')"
#Don't want smiley right now
#local SMILEY="if [ \$? != 0 ]; then echo \"${RED}:(${RESET}\"; else echo \"${LIGHTGREEN}:)${RESET}\"; fi"
export PS1="\`${SMILEY}\`[${MAGENTA}\u${RESET}@${MAGENTA}\h ${RESET}${BOLD}${GREEN}\w${RESET}]${RED}${GIT}${RESET}\\$ "
}
set_ps1

# Makes bash check how large the window is
shopt -s checkwinsize

export EDITOR="vim"

if [[ -h ~/bin ]]; then
    PATH=$PATH:~/bin
fi
if [[ -d /opt/android-sdk ]]; then
    PATH=$PATH:/opt/android-sdk/platform-tools:/opt/android-sdk/tools
fi
if [[ -d ~/prog/pintos/bin ]]; then
    PATH=$PATH:~/prog/pintos/bin
fi

PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"

unzip () {
	command unzip "$@" -x "*__MACOSX*" "*.DS_Store*"
}

alias ls='ls --color=auto'
alias vim="nvim -p"

alias chromiumdev="chromium --user-data-dir=/home/maistho/chromedev --disable-web-security"
alias git-blame-count="git ls-tree --name-only -z -r HEAD|egrep -z -Z -E '\.(cc|h|cpp|hpp|c|txt|html|js|css|xml)$'|xargs -0 -n1 git blame --line-porcelain|grep '^author '|sort|uniq -c|sort -nr"


#Temp android-studio fix
alias android-studio="_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on' android-studio"

# etckeeper
alias pkg-update='sudo etckeeper pre-install && sudo pacman -Syu && sudo etckeeper post-install'


#Avoid duplicates in bash_history
export HISTCONTROL=ignoredups:erasedups
# Save bash history after each command
shopt -s histappend                      # append to history, don't overwrite it
export PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"


alias playmusic='chromium --profile-directory=Default --app-id=icppfcnhkcmnfdhfhphakoifcfokfdhg'

export NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$NPM_PACKAGES/bin:$PATH"



export NVM_DIR="/home/maistho/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
