" Auto stuff
" Remove trailing whitespaces on all lines
autocmd BufWritePre * :%s/\s\+$//e

" Remember the position of the cursor
function! ResCur()
	if line("'\"") <= line("$")
		normal! g`"
		return 1
	endif
endfunction

augroup resCur
	autocmd!
	autocmd BufWinEnter * call ResCur()
augroup END

"-

" Vundle setup
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

filetype plugin indent on

" Bundles
Bundle "pangloss/vim-javascript"

Bundle "mustache/vim-mustache-handlebars"
let g:mustache_abbreviations = 1

Bundle "Valloric/MatchTagAlways"
let g:mta_set_default_matchtag_color = 1
highlight MatchParen ctermfg=black ctermbg=lightgrey guibg=lightgreen

" Bundle 'jelera/vim-javascript-syntax'
"au FileType javascript call JavaScriptFold()

Bundle "godlygeek/tabular"

" Set filetype mustache for handlebars
autocmd BufNewFile,Bufread *.handlebars setfiletype mustache

" Basic stuff
set nocompatible
set backspace=2
syntax on
colorscheme vim-distinguished/colors/distinguished
set showcmd
set nohidden
set lbr

" Use line numbers
set number

" Set proper tabs and indents
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

" Set completion
set wildmenu

" Allow use of mouse
set mouse=a

" Search with smart case sensitivity
set ignorecase
set smartcase

set incsearch
set hlsearch
set grepprg=grep\ -H\ $*

" Persistent undo
" not working? TODO: check why
set undodir=~/.vim/undodir
set undofile
set undolevels=1000
set undoreload=10000

" Remaps
nnoremap <F5> gg=G''
inoremap <F5> <Esc>gg=G''
inoremap jj <Esc>
inoremap <F7> <Esc>:tabp<CR>
inoremap <F8> <Esc>:tabn<CR>
nnoremap <F8> :tabn<CR>
nnoremap <F7> :tabp<CR>
